name: Generate docs

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - uses: hashicorp/setup-terraform@v3

      - name: Generate doc
        run: go generate ./...

      - uses: actions/upload-artifact@v4
        with:
          name: generated-docs
          path: docs/
